variable "name" {
  description = "Server name, globally unique (becomes <name>.<private dns zone>)."
  type        = string
}

variable "resource_group_name" {
  description = "Existing resource group."
  type        = string
}

variable "location" {
  description = "Azure region."
  type        = string
}

variable "postgres_version" {
  description = "PostgreSQL major version."
  type        = string
  default     = "16"
}

variable "sku_name" {
  description = "Flexible Server SKU, tier_Standard_size: B_Standard_B1ms / B_Standard_B2s (Burstable), GP_Standard_D2ds_v5 (General Purpose)."
  type        = string
}

variable "storage_mb" {
  description = "Initial storage in MB (32768 = 32 GB). Auto-grow is on; storage can only be increased."
  type        = number
  default     = 32768
}

variable "administrator_login" {
  description = "Administrator login name."
  type        = string
  default     = "hsadmin"
}

variable "administrator_password" {
  description = "Administrator password (generated by the keyvault module)."
  type        = string
  sensitive   = true
}

variable "database_name" {
  description = "Application database."
  type        = string
  default     = "homeschool"
}

variable "delegated_subnet_id" {
  description = "Subnet delegated to Microsoft.DBforPostgreSQL/flexibleServers."
  type        = string
}

variable "private_dns_zone_id" {
  description = "Private DNS zone ID (must already be linked to the VNet; the network module's output guarantees that ordering)."
  type        = string
}

variable "backup_retention_days" {
  description = "Backup retention, 7 to 35 days."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_days >= 7 && var.backup_retention_days <= 35
    error_message = "backup_retention_days must be between 7 and 35."
  }
}

variable "geo_redundant_backup_enabled" {
  description = "Copy backups to the paired region. Cannot be changed after the server is created."
  type        = bool
  default     = false
}

variable "high_availability_mode" {
  description = "null = no standby (default, cheaper). ZoneRedundant = standby in another zone (roughly doubles compute cost). SameZone = standby in the same zone."
  type        = string
  default     = null

  validation {
    condition     = var.high_availability_mode == null || contains(["ZoneRedundant", "SameZone"], coalesce(var.high_availability_mode, "x"))
    error_message = "high_availability_mode must be null, ZoneRedundant or SameZone. Burstable SKUs do not support high availability."
  }
}

variable "prevent_destroy" {
  description = "Adds lifecycle.prevent_destroy (true for prod). Terraform cannot make prevent_destroy conditional, so the module contains two identical server resources and picks one with count. Do NOT flip this on an existing server: use terraform state mv, or Terraform will try to destroy and recreate the database."
  type        = bool
  default     = false
}

variable "maintenance_window_day_of_week" {
  description = "0 = Sunday. UTC."
  type        = number
  default     = 0
}

variable "maintenance_window_start_hour" {
  description = "Start hour in UTC (20 = 01:30 IST the next day)."
  type        = number
  default     = 20
}

variable "maintenance_window_start_minute" {
  description = "Start minute (UTC)."
  type        = number
  default     = 0
}

variable "tags" {
  description = "Tags applied to every resource."
  type        = map(string)
}
